#!/bin/sh


TEMPLATE="bolt_values = {
  \"REACT_APP_HASURA_WS_URL\": \"$REACT_APP_HASURA_WS_URL\",
  \"REACT_APP_HASURA_API_URL\": \"$REACT_APP_HASURA_API_URL\",
  \"REACT_APP_AUTH_SERVICE\": \"$REACT_APP_AUTH_SERVICE\",
  \"REACT_APP_API_SERVICE_BASE_URL\": \"$REACT_APP_API_SERVICE_BASE_URL\",
  \"REACT_APP_ARGO_URL\": \"$REACT_APP_ARGO_URL\",
  \"REACT_APP_AUTH0_AUDIENCE\": \"$REACT_APP_AUTH0_AUDIENCE\",
  \"REACT_APP_AUTH0_CLIENT_ID\": \"$REACT_APP_AUTH0_CLIENT_ID\",
  \"REACT_APP_AUTH0_DOMAIN\": \"$REACT_APP_AUTH0_DOMAIN\",
}"


if [ -d "public/" ]; then
  RES_PATH="public/res.js"
else
  RES_PATH="/usr/share/nginx/html/res.js"
fi
echo "$TEMPLATE" > $RES_PATH
