-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."execution" add column "cpu_warning" boolean
--  not null default 'false';
