-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- ALTER TABLE "public"."execution" ADD COLUMN "argo_namespace" text DEFAULT 'default'::text NOT NULL;