table:
  schema: public
  name: configuration_type
array_relationships:
  - name: configurations
    using:
      foreign_key_constraint_on:
        column: type_slug
        table:
          schema: public
          name: configuration
  - name: parameters
    using:
      foreign_key_constraint_on:
        column: type_slug
        table:
          schema: public
          name: parameter
  - name: repositories
    using:
      foreign_key_constraint_on:
        column: type_slug
        table:
          schema: public
          name: repository
select_permissions:
  - role: manager
    permission:
      columns:
        - id
        - name
        - description
        - slug_name
      filter: {}
      allow_aggregations: true
  - role: reader
    permission:
      columns:
        - description
        - id
        - name
        - slug_name
      filter: {}
      allow_aggregations: true
  - role: tenantadmin
    permission:
      columns:
        - id
        - name
        - description
        - slug_name
      filter: {}
      allow_aggregations: true
  - role: tester
    permission:
      columns:
        - description
        - id
        - name
        - slug_name
      filter: {}
      allow_aggregations: true
