table:
  schema: public
  name: configuration
object_relationships:
  - name: configuration_type
    using:
      foreign_key_constraint_on: type_slug
  - name: project
    using:
      foreign_key_constraint_on: project_id
  - name: test_source
    using:
      foreign_key_constraint_on: test_source_id
array_relationships:
  - name: configuration_envvars
    using:
      foreign_key_constraint_on:
        column: configuration_id
        table:
          schema: public
          name: configuration_envvars
  - name: configuration_extensions
    using:
      foreign_key_constraint_on:
        column: configuration_id
        table:
          schema: public
          name: configuration_extension
  - name: configuration_parameters
    using:
      foreign_key_constraint_on:
        column: configuration_id
        table:
          schema: public
          name: configuration_parameter
  - name: executions
    using:
      foreign_key_constraint_on:
        column: configuration_id
        table:
          schema: public
          name: execution
  - name: test_runs
    using:
      foreign_key_constraint_on:
        column: scenario_id
        table:
          schema: public
          name: test_run
select_permissions:
  - role: manager
    permission:
      columns:
        - id
        - name
        - project_id
        - performed
        - created_by_id
        - type_slug
        - test_source_id
        - instances
        - is_deleted
        - has_pre_test
        - has_post_test
        - has_load_tests
        - has_monitoring
        - monitoring_chart_configuration
      filter:
        _and:
          - project:
              userProjects:
                user_id:
                  _eq: X-Hasura-User-Id
          - project:
              is_deleted:
                _eq: false
          - is_deleted:
              _eq: false
      allow_aggregations: true
  - role: reader
    permission:
      columns:
        - id
        - name
        - project_id
        - performed
        - created_by_id
        - type_slug
        - test_source_id
        - instances
        - is_deleted
        - has_pre_test
        - has_post_test
        - has_load_tests
        - has_monitoring
        - monitoring_chart_configuration
      filter:
        _and:
          - project:
              userProjects:
                user_id:
                  _eq: X-Hasura-User-Id
          - project:
              is_deleted:
                _eq: false
          - is_deleted:
              _eq: false
      allow_aggregations: true
  - role: tenantadmin
    permission:
      columns:
        - id
        - name
        - project_id
        - performed
        - created_by_id
        - type_slug
        - test_source_id
        - instances
        - is_deleted
        - has_pre_test
        - has_post_test
        - has_load_tests
        - has_monitoring
        - monitoring_chart_configuration
      filter:
        _and:
          - project:
              userProjects:
                user_id:
                  _eq: X-Hasura-User-Id
          - project:
              is_deleted:
                _eq: false
          - is_deleted:
              _eq: false
      allow_aggregations: true
  - role: tester
    permission:
      columns:
        - id
        - name
        - project_id
        - performed
        - created_by_id
        - type_slug
        - test_source_id
        - instances
        - is_deleted
        - has_pre_test
        - has_post_test
        - has_load_tests
        - has_monitoring
        - monitoring_chart_configuration
      filter:
        _and:
          - project:
              userProjects:
                user_id:
                  _eq: X-Hasura-User-Id
          - project:
              is_deleted:
                _eq: false
          - is_deleted:
              _eq: false
      allow_aggregations: true
  - role: testrunner
    permission:
      columns:
        - created_by_id
        - has_load_tests
        - has_monitoring
        - has_post_test
        - has_pre_test
        - id
        - instances
        - name
        - performed
        - project_id
        - test_source_id
        - type_slug
      filter:
        _and:
          - executions:
              id:
                _eq: X-Hasura-Testruner-Id
          - project:
              is_deleted:
                _eq: false
          - is_deleted:
              _eq: false
