table:
  schema: public
  name: configuration_monitoring
object_relationships:
  - name: configuration
    using:
      foreign_key_constraint_on: configuration_id
array_relationships:
  - name: monitoring_metrics
    using:
      foreign_key_constraint_on:
        column: monitoring_id
        table:
          schema: public
          name: monitoring_metric
insert_permissions:
  - role: tenantadmin
    permission:
      check:
        _and:
          - configuration:
              is_deleted:
                _eq: false
          - configuration:
              project:
                is_deleted:
                  _eq: false
          - configuration:
              project:
                userProjects:
                  user_id:
                    _eq: X-Hasura-User-Id
      columns:
        - chart_type
        - query
        - configuration_id
        - id
      backend_only: false
select_permissions:
  - role: reportgenerator
    permission:
      columns:
        - chart_type
        - query
        - unit
        - configuration_id
        - id
      filter: {}
  - role: tenantadmin
    permission:
      columns:
        - chart_type
        - configuration_id
        - id
        - query
        - unit
      filter: {}
update_permissions:
  - role: tenantadmin
    permission:
      columns:
        - chart_type
        - query
        - configuration_id
        - id
      filter:
        _and:
          - configuration:
              is_deleted:
                _eq: false
          - configuration:
              project:
                is_deleted:
                  _eq: false
          - configuration:
              project:
                userProjects:
                  user_id:
                    _eq: X-Hasura-User-Id
      check: null
delete_permissions:
  - role: tenantadmin
    permission:
      filter:
        _and:
          - configuration:
              is_deleted:
                _eq: false
          - configuration:
              project:
                is_deleted:
                  _eq: false
          - configuration:
              project:
                userProjects:
                  user_id:
                    _eq: X-Hasura-User-Id
