import enum


REQUIRED_ENV_VARS = {"EXECUTION_ID", "BOLT_GRAPHQL_URL", "BOLT_HASURA_TOKEN", "BOLT_WS_URL"}


class ExecutionStatuses(enum.Enum):
    FINNISHED = "FINISHED"
    TERMINATED = "TERMINATED"
    PENDING = "PENDING"
