-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."execution_requests" add column "successes_per_tick" numeric
--  not null;
