version: '2'

services:
  builder:
    build:
      context: .
    command: [ "/bin/bash", "-c", "--", "while true; do sleep 30; done;" ]
    volumes:
      - ~/.ssh:/root/.ssh:ro
      - ./creds.json:/builder/creds.json
      - ./builder:/builder
